"""Regenerate the class emblems and the name table they are looked up by.

Two things come out of one source so they cannot drift apart:

    assets/breeds/<id>.png   the class symbol, 48x48 RGBA
    src/breeds.rs            every language's spelling of every class

The name table is the part that matters. The window title gives the class
in the LANGUAGE OF THE PLAYER'S CLIENT - a Spanish client says "Yopuka"
where an English one says "Iop" - so a table written from the English
names alone recognises nothing at all for most of Europe, and does it
silently: the row simply keeps the plain dot it always had. Five languages
are published, so all five go in the table whether or not the app's own
interface speaks them.

48px because the panel's slot is 24 logical pixels and a 200% display
doubles it; anything above that is weight in the executable for pixels no
monitor asks for.

    python tools/fetch_breeds.py

Needs Pillow and network. Run it when Ankama adds a class - nothing else
regenerates it, and a missing class falls back to the plain dot rather
than to a wrong emblem.
"""

import json
import os
import unicodedata
import urllib.request

from PIL import Image

API = "https://api.dofusdb.fr/breeds?$limit=50"
TILE = 48
# Empty tile left around the trimmed mark, so the panel's edge glow has
# room to spread instead of being clipped flat against the tile's border.
MARGIN = 4
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ART = os.path.join(ROOT, "assets", "breeds")
TABLE = os.path.join(ROOT, "src", "breeds.rs")

# The languages the game itself is published in. The app's own interface is
# English, French and Spanish; a player may still be running a German or
# Portuguese client, and that client writes its own language in the title.
LANGS = ("en", "fr", "es", "de", "pt")


def fold(name):
    """Lowercase, accents removed - "Cra", "Crâ" and "CRA" are one key.

    The title is read from the window as the game wrote it, so the accents
    are real. Comparing folded on both sides means the table can be read
    as plain ASCII and still match what arrives.
    """
    flat = unicodedata.normalize("NFD", name)
    flat = "".join(c for c in flat if unicodedata.category(c) != "Mn")
    return flat.lower().strip()


def fetch():
    with urllib.request.urlopen(API, timeout=60) as response:
        return sorted(json.load(response)["data"], key=lambda b: b["id"])


def names_of(breed):
    """Every spelling of this class, folded, without duplicates.

    Both the short name ("Iop") and the long one are taken: which of the
    two the client writes in its title is the game's choice, not ours, and
    carrying both costs a string.
    """
    seen = []
    for field in ("shortName", "longName"):
        table = breed.get(field) or {}
        for lang in LANGS:
            key = fold(table.get(lang) or "")
            if key and key not in seen:
                seen.append(key)
    return seen


def save_art(breed):
    """Trim the transparent margin, then centre what is left in the tile.

    The source art is not consistently framed: some symbols sit dead centre
    in their square, others are pushed to a corner with a wide empty band
    down one side. Resizing the raw square meant the panel centred the
    TILE rather than the MARK, so a row's emblem sat visibly off to one
    side, and a symbol with a lot of padding drew smaller than its
    neighbours for no reason a reader could see - the two complaints are
    one bug.

    Trimming to the alpha bounding box and fitting THAT to the tile fixes
    both at once, and doing it on the full-size source rather than on the
    downscaled copy means nothing is enlarged from pixels already thrown
    away. MARGIN keeps a ring of empty tile around the mark so the glow
    the panel draws round its edge has somewhere to go.
    """
    url = breed["img"]
    raw = os.path.join(ART, f"_{breed['id']}.src")
    urllib.request.urlretrieve(url, raw)
    source = Image.open(raw).convert("RGBA")

    box = source.split()[3].getbbox()
    if box:
        source = source.crop(box)

    inner = TILE - MARGIN * 2
    fit = min(inner / source.width, inner / source.height)
    size = (max(1, round(source.width * fit)), max(1, round(source.height * fit)))
    mark = source.resize(size, Image.LANCZOS)

    tile = Image.new("RGBA", (TILE, TILE), (0, 0, 0, 0))
    tile.paste(mark, ((TILE - size[0]) // 2, (TILE - size[1]) // 2), mark)
    tile.save(os.path.join(ART, f"{breed['id']}.png"))
    os.remove(raw)


def write_table(breeds):
    lines = [
        "//! Every class, and every spelling of it a client may put in its title.",
        "//!",
        "//! Generated by tools/fetch_breeds.py - do not edit by hand. The names",
        "//! are folded (lowercase, no accents) so the lookup can fold the title",
        "//! the same way and compare plain ASCII; `emblem.rs` draws the artwork",
        "//! that sits beside each id.",
        "",
        "/// (class id, every folded name that means it). The id is the game's",
        "/// own and is what assets/breeds/<id>.png is named after.",
        f"pub const BREEDS: [(u32, &[&str]); {len(breeds)}] = [",
    ]
    for breed in breeds:
        names = ", ".join(f"\"{n}\"" for n in names_of(breed))
        lines.append(f"    ({breed['id']}, &[{names}]),")
    lines += [
        "];",
        "",
        "/// Lowercase, accents removed, so \"Cra\" and \"Cr\\u{e2}\" are one key.",
        "fn fold(name: &str) -> String {",
        "    name.trim()",
        "        .chars()",
        "        .flat_map(|c| c.to_lowercase())",
        "        .map(|c| match c {",
        "            '\\u{e0}'..='\\u{e5}' => 'a',",
        "            '\\u{e7}' => 'c',",
        "            '\\u{e8}'..='\\u{eb}' => 'e',",
        "            '\\u{ec}'..='\\u{ef}' => 'i',",
        "            '\\u{f1}' => 'n',",
        "            '\\u{f2}'..='\\u{f6}' | '\\u{f8}' => 'o',",
        "            '\\u{f9}'..='\\u{fc}' => 'u',",
        "            '\\u{fd}' | '\\u{ff}' => 'y',",
        "            other => other,",
        "        })",
        "        .collect()",
        "}",
        "",
        "/// The class this breed name means, or None when it means none of",
        "/// them. None is a real answer: a client language nobody has added, a",
        "/// class added after this table was generated, or a window that is not",
        "/// a game at all. The panel draws its plain dot for it rather than",
        "/// guessing at an emblem.",
        "pub fn id_for(breed: &str) -> Option<u32> {",
        "    let key = fold(breed);",
        "    if key.is_empty() {",
        "        return None;",
        "    }",
        "    BREEDS",
        "        .iter()",
        "        .find(|(_, names)| names.contains(&key.as_str()))",
        "        .map(|(id, _)| *id)",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    /// No two classes may answer to the same name, in any language.",
        "    /// A collision would send a row to the wrong emblem and never say",
        "    /// so, which is the one failure this table can have.",
        "    #[test]",
        "    fn every_name_means_one_class() {",
        "        let mut seen: Vec<(&str, u32)> = Vec::new();",
        "        for (id, names) in BREEDS {",
        "            for name in names {",
        "                if let Some((_, other)) = seen.iter().find(|(n, _)| n == name) {",
        "                    panic!(\"{name} means both {other} and {id}\");",
        "                }",
        "                seen.push((name, id));",
        "            }",
        "        }",
        "    }",
        "",
        "    /// The title is read as the client wrote it, accents and all.",
        "    #[test]",
        "    fn reads_a_title_in_any_language() {",
        "        assert_eq!(id_for(\"Iop\"), id_for(\"Yopuka\"));",
        "        assert_eq!(id_for(\"Cr\\u{e2}\"), id_for(\"Cra\"));",
        "        assert_eq!(id_for(\"X\\u{e9}lor\"), id_for(\"Xelor\"));",
        "        assert_eq!(id_for(\"  iop  \"), id_for(\"Iop\"));",
        "        assert_eq!(id_for(\"Zurcar\\u{e1}k\"), id_for(\"Ecaflip\"));",
        "        assert_eq!(id_for(\"\"), None);",
        "        assert_eq!(id_for(\"Bontarien\"), None);",
        "    }",
        "}",
        "",
    ]
    with open(TABLE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main():
    os.makedirs(ART, exist_ok=True)
    breeds = fetch()

    # A name that means two classes would send a row to the wrong emblem in
    # silence, so it stops the generator rather than reaching the table.
    claimed = {}
    for breed in breeds:
        for name in names_of(breed):
            if name in claimed:
                raise SystemExit(f"{name!r} means both {claimed[name]} and {breed['id']}")
            claimed[name] = breed["id"]

    for breed in breeds:
        save_art(breed)
    write_table(breeds)
    print(f"{len(breeds)} classes, {len(claimed)} names -> {TABLE}")


if __name__ == "__main__":
    main()
