//! Every class, and every spelling of it a client may put in its title.
//!
//! Generated by tools/fetch_breeds.py - do not edit by hand. The names
//! are folded (lowercase, no accents) so the lookup can fold the title
//! the same way and compare plain ASCII; `emblem.rs` draws the artwork
//! that sits beside each id.

/// (class id, every folded name that means it). The id is the game's
/// own and is what assets/breeds/<id>.png is named after.
pub const BREEDS: [(u32, &[&str]); 19] = [
    (1, &["feca"]),
    (2, &["osamodas"]),
    (3, &["enutrof", "anutrof"]),
    (4, &["sram"]),
    (5, &["xelor"]),
    (6, &["ecaflip", "zurcarak"]),
    (7, &["eniripsa", "aniripsa"]),
    (8, &["iop", "yopuka"]),
    (9, &["cra", "ocra"]),
    (10, &["sadida"]),
    (11, &["sacrier", "sacrieur", "sacrogrito"]),
    (12, &["pandawa"]),
    (13, &["rogue", "roublard", "tymador", "halsabschneider", "ladino"]),
    (14, &["masqueraider", "zobal", "maskerador"]),
    (15, &["foggernaut", "steamer"]),
    (16, &["eliotrope", "selotrop", "eliotrop"]),
    (17, &["huppermage", "hipermago", "ubermagier", "huppermago"]),
    (18, &["ouginak", "uginak", "kilorf"]),
    (20, &["forgelance", "forjalanza", "speerschmied", "forjalanca"]),
];

/// Lowercase, accents removed, so "Cra" and "Cr\u{e2}" are one key.
fn fold(name: &str) -> String {
    name.trim()
        .chars()
        .flat_map(|c| c.to_lowercase())
        .map(|c| match c {
            '\u{e0}'..='\u{e5}' => 'a',
            '\u{e7}' => 'c',
            '\u{e8}'..='\u{eb}' => 'e',
            '\u{ec}'..='\u{ef}' => 'i',
            '\u{f1}' => 'n',
            '\u{f2}'..='\u{f6}' | '\u{f8}' => 'o',
            '\u{f9}'..='\u{fc}' => 'u',
            '\u{fd}' | '\u{ff}' => 'y',
            other => other,
        })
        .collect()
}

/// The class this breed name means, or None when it means none of
/// them. None is a real answer: a client language nobody has added, a
/// class added after this table was generated, or a window that is not
/// a game at all. The panel draws its plain dot for it rather than
/// guessing at an emblem.
pub fn id_for(breed: &str) -> Option<u32> {
    let key = fold(breed);
    if key.is_empty() {
        return None;
    }
    BREEDS
        .iter()
        .find(|(_, names)| names.contains(&key.as_str()))
        .map(|(id, _)| *id)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// No two classes may answer to the same name, in any language.
    /// A collision would send a row to the wrong emblem and never say
    /// so, which is the one failure this table can have.
    #[test]
    fn every_name_means_one_class() {
        let mut seen: Vec<(&str, u32)> = Vec::new();
        for (id, names) in BREEDS {
            for name in names {
                if let Some((_, other)) = seen.iter().find(|(n, _)| n == name) {
                    panic!("{name} means both {other} and {id}");
                }
                seen.push((name, id));
            }
        }
    }

    /// The title is read as the client wrote it, accents and all.
    #[test]
    fn reads_a_title_in_any_language() {
        assert_eq!(id_for("Iop"), id_for("Yopuka"));
        assert_eq!(id_for("Cr\u{e2}"), id_for("Cra"));
        assert_eq!(id_for("X\u{e9}lor"), id_for("Xelor"));
        assert_eq!(id_for("  iop  "), id_for("Iop"));
        assert_eq!(id_for("Zurcar\u{e1}k"), id_for("Ecaflip"));
        assert_eq!(id_for(""), None);
        assert_eq!(id_for("Bontarien"), None);
    }
}
